export const PARSING_ERROR_CODES = {
    INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
    PARSING_FAILED: 'PARSING_FAILED',
    DOCX_PARSE_FAILED: 'DOCX_PARSE_FAILED',
    LATEX_PARSE_FAILED: 'LATEX_PARSE_FAILED',
    TXT_PARSE_FAILED: 'TXT_PARSE_FAILED',
    XML_PARSE_FAILED: 'XML_PARSE_FAILED',
    TELEFORM_PARSE_FAILED: 'TELEFORM_PARSE_FAILED',
} as const;

export type ParsingErrorCode = (typeof PARSING_ERROR_CODES)[keyof typeof PARSING_ERROR_CODES];
