FROM node:20-slim

WORKDIR /app


RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      libreoffice-writer \
      libreoffice-calc \
      libreoffice-impress \
      fonts-dejavu-core \
      fontconfig && \
    rm -rf /var/lib/apt/lists/*


COPY package*.json ./
RUN npm install


RUN npm install -g ts-node nodemon

CMD ["npm", "run", "dev"]
